server:
  port: 1234

spring:
  cloud:
    gateway:
      #      default-filters:
      #          - name: RequestRateLimiter
      #            args:
      #              redis-rate-limiter.replenish-rate: 10
      #              redis-rate-limiter.burst-capacity: 20
      #              key-resolver: "#{@userKeyResolver}"

     key-resolver: "#{@userKeyResolver}"

  redis:
    host: localhost
    port: 6379

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/apigw
    username: postgres
    password: qwerty
    validationQuery: SELECT 1
    maxTotal: 10
    maxIdle: 10
    initialSize: 5
    defaultAutoCommit: false
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: true
    poolPreparedStatements: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka

logging:
  level:
    com.example.gatewaydemo: debug
    org.springframework: debug

clientRateLimit:
  scope: local
  type: clientId #hostName, IP
  replenishRate: 10
  burstCapacity: 10
